### ISSUE TITLE
Recognized symbols not available as definitions (tniASM specific issue?)

### ISSUE THREAD

**Issue by theNestruo** [mborik/z80-macroasm-vscode#10]
Hello!

In my tniASM 0.45 projects (e.g.: the include-heavy [msx-msxlib](https://github.com/theNestruo/msx-msxlib) or the much simpler [msx-pyramidwarpex](https://github.com/theNestruo/msx-pyramidwarpex)) no definitions are available:
![image](https://user-images.githubusercontent.com/12213477/90959199-c5548000-e499-11ea-842a-dd1ad7bca41a.png)

However, they appear in the outline view:
![image](https://user-images.githubusercontent.com/12213477/90959254-28dead80-e49a-11ea-9d2d-6e2d9df877f6.png)

And also appear when I "Go to Symbol in Workspace...":
![image](https://user-images.githubusercontent.com/12213477/90959262-41e75e80-e49a-11ea-8a10-60e3666c7c60.png)

Note 1: In other projects using different assemblers (e.g.: [this one](https://github.com/GuillianSeed/MetalGear) that uses Sjasm 0.39) definitions are correctly found and available.

Note 2: I don't know if it is related to this issue or if it is just a red herring, but assembler directives (IFDEF / IFEXIST / ENDIF) are recognized as symbols:
![image](https://user-images.githubusercontent.com/12213477/90959453-8c1d0f80-e49b-11ea-94af-96c4dc61c76b.png)

Thanks!

**Comment by ammehet** [comment]
Hello there!

Probably the same issue.
Let me start with a simple snippet. All is fine, definition found:
![Screen Shot 2020-08-23 at 00 21 25](https://user-images.githubusercontent.com/47472465/90966234-d2dd2a80-e4d8-11ea-87b5-f9348f1041da.png)
Now let us introduce some plan for the future, which is not exists at the time:
![Screen Shot 2020-08-23 at 00 23 59](https://user-images.githubusercontent.com/47472465/90966341-1f753580-e4da-11ea-8272-c1850f72bb82.png)
No way. Well, let's comment it out for future use
![Screen Shot 2020-08-23 at 00 26 49](https://user-images.githubusercontent.com/47472465/90966421-d376c080-e4da-11ea-9952-19a5acc710ef.png)
Again, no luck. Well, let's comment this from the beginning of the line
![Screen Shot 2020-08-23 at 00 27 42](https://user-images.githubusercontent.com/47472465/90966520-fbb2ef00-e4db-11ea-84bf-2d9120b0646b.png)
And yes, shall we go!

But what if the future is almost here and it's time to implement the plan? Let us create an empty file
![Screen Shot 2020-08-23 at 00 28 56](https://user-images.githubusercontent.com/47472465/90966582-8eec2480-e4dc-11ea-9069-978c51f6423f.png)
Looks pretty fine even if we change our minds halfway with the file still does not exists
![Screen Shot 2020-08-23 at 01 11 36](https://user-images.githubusercontent.com/47472465/90966688-040c2980-e4de-11ea-9880-2f20b745cc5b.png)

P.S.
Turns out, it doesn't matter if you `include` something into the project, just put random file containing a certain line into the project directory
![Screen Shot 2020-08-23 at 02 00 50](https://user-images.githubusercontent.com/47472465/90967211-9ca5a800-e4e4-11ea-82bd-c07bebb2d8a6.png)

**Comment by mborik** [comment]
Yeah, I struggled with something similar while development of my [Regression](https://github.com/mborik/regression) [demo](https://www.youtube.com/watch?v=RKRRla9x8Vw) and I know how it's terribly annoying. In these situations helps me to restart extension host _(through `F1` menu)_ and z80-macroasm reloaded all current symbols.
Anyway, thank you guys 👍 for your detailed issue description and steps to reproduce.
I will trace and debug it and try to find solution.

**Comment by theNestruo** [comment]
Hi, @mborik !

I was just doing a quick tests, and found something that may shed some light on the origin of the issue: the problem seems to have appeared between versions 0.5.0 and 0.6.0 (meaning it was ok in 0.5.0 and started to fail in 0.6.0).

**Comment by mborik** [comment]
@theNestruo @ammehet
Guys, please check the release [v0.7.0](https://github.com/mborik/z80-macroasm-vscode/releases/tag/v0.7.0) if your issues was solved. Thanks. 😉

**Comment by theNestruo** [comment]
Yes, it is solved! Thank you very much!!! :D
