### ISSUE TITLE
Labelled empty line formatted to `undefined`

### ISSUE THREAD

**Issue by mborik** [mborik/z80-macroasm-vscode#12]
Reported by @alexanderk23 and @kolnogorov

If label was typed without colon but assigned to empty line (which is quite a common case), `undefined` is inserted in the line after formatter was applied.

![image](https://user-images.githubusercontent.com/1952738/110912681-83dfd100-8314-11eb-8b55-75b37131bbbf.png)

**Comment by tomaz** [comment]
This happens for labels with colon as well...

**Comment by mborik** [comment]
@alexanderk23, @kolnogorov, @tomaz 
Guys, I cannot reproduce this issue with my latest fixes and improvements added.
Can I ask you to re-test this issue with latest v0.7.3 version? 🙏 
Please, enable the formatter first, set `z80-macroasm.format.enabled` to `true` in settings and restart extension host.

**Comment by tomaz** [comment]
Seems to be better, but still not working fully:

in `"editor.formatOnSaveMode": "modifications"` mode:
- works for pre-existing labels
- still adds `undefined` to newly created labels
- though it's weird, because it insists on adding `undefined` to newly created labels even after I restart VS Code (in which case I'd expect that those would be treated as "pre-existing" 🤔)

in `"editor.formatOnSaveMode": "file"` mode:
- still inserts `undefined` universally (to pre-existing and new labels)

I use `"editor.formatOnSave": true` in case this affects something... Let me know if you need additional info from me. I'm not familiar with VS Code extensions, but if it's possible to test directly from github branch without actually releasing, I can do that (with some tips on how to set it up 😅)

**Comment by mborik** [comment]
Thanks a lot for your detailed test-scenario and steps to reproduce the issue. I should debug it very carefully.

To test extension from actual branch:
- **Git** and latest **Node.js** installed locally
- `git clone https://github.com/mborik/z80-macroasm-vscode.git`
- `code z80-macroasm-vscode` or open project dir in VSCode
- open intergrated terminal
- `npm install`
- `npm run compile`
- Run > Start debugging (or simply press F5)

**Comment by tomaz** [comment]
Great thanks! Was able to run the extension (on `master`) and it seems the issue arrives on line 253 of `formatProcessor.ts`; `lineParts.fragments` is `undefined` (seems to be missing from `lineParts` altogether). But after that `foreach` it gets added to the end of `newText` array and then of course gets rendered to the line from there...

I'm not familiary with JS, so not really sure if this is simply due to `fragments` property is not set in `lineParts`. If I embed the whole `forEach` block like this, it seems to work (but the code is ugly, I'm sure you'll find much better way, besides, I'm not even sure this doesn't create another issue):

```
(lineParts.fragments || [{ ...lineParts }]).forEach(
	({ keyword, firstParam, args = [] }, index) => {
		if (keyword !== undefined) {
			... (existing code)
		}
	}
);
```

And the reason for "pre-existing" labels working is simply due to use of `"editor.formatOnSaveMode": "modifications"` not reporting them! Which is a good thing in a way - because the issue is consistent 😅.

I hope this helps, if you want me to test some changes, just let me know! I can also try it from another branch.

![image](https://user-images.githubusercontent.com/77294/121368792-9f6e6e00-c93b-11eb-8ecd-2fdf6401548a.png)

**Comment by mborik** [comment]
@tomaz Believe or not, origin of the issue was your `whitespaceAfterInstruction` setting and this was reason why I cannot reproduce it because I haven't saw a connection to this setting.
When that setting was set to something not automatical, additional formatting of `keyword` happen so `undefined` was converted into text. 🤦 

Funny, but hey, it's fixed now! 😁 
Huge thanks!

**Comment by tomaz** [comment]
Nice! What can I say, I have unique taste (some would call it OCD) 😀 Had a feeling I was fixing the leaves instead of the roots, but glad I could help! And it was fun seeing how extensions work!
